// us
[timing.intervals]
sample = 2000
adjust = 20_000
finetune = 1_000_000_000

// MHz/ms
[timing.ramp-rates]
normal = 1
burst = 200

// # samples in a row
[timing]
burst-samples = 48

# MHz
[frequency-thresholds]
adjust = 100
finetune = 10

[load-target]
upper = 0.95
lower = 0.7

[[safe-points]]
frequency = 350 # MHz
voltage = 700 # mV

[[safe-points]]
frequency = 2000
voltage = 1000

